#eg. 2 .github/workflows/first_job.yml

name: First Workflow

on:
  - push

jobs:
  first_job:
    name: jomacs-k8s
    runs-on: ubuntu-latest
    steps:
      - name: First Message
        run: echo "Welome to the World of CICD through GitHub Actions"

      - name: List All Files  including hidden
        run: ls -1a

      - name: Sow Present Working Directory
        run: pwd
